# Generated by Django 3.0.3 on 2020-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
