# Generated by Django 3.0.3 on 2020-12-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20201205_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
