# Generated by Django 3.0.3 on 2020-12-05 12:18

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20201205_1740'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercreate',
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
